ColoradoBeetle.UI/Controllers/ShoppingListController.cs
    using ColoradoBeetle.Application.ShoppingLists.Commands.AddShopinngList;
using ColoradoBeetle.Application.ShoppingLists.Commands.DeleteShoppingList;
using ColoradoBeetle.Application.ShoppingLists.Commands.EditShoppingList;
using ColoradoBeetle.Application.ShoppingLists.Queries.GetEditShoppingList;
using ColoradoBeetle.Application.ShoppingLists.Queries.GetShoppingListForCopy;
using ColoradoBeetle.Application.ShoppingLists.Queries.GetShoppingLists;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ColoradoBeetle.UI.Controllers; 

[Authorize]
public class ShoppingListController : BaseController {
    private readonly ILogger<ShoppingListController> _logger;

    public ShoppingListController(ILogger<ShoppingListController> logger)
    {
        _logger = logger;
    }
    public async Task<IActionResult> ShoppingLists() {

        return View(await Mediator.Send(new GetShoppingListsQuery {UserId = UserId }));
    }

    public IActionResult AddShoppingList() {

        return View(new AddShoppingListCommand());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddShoppingList(AddShoppingListCommand command) {

        var result = await MediatorSendValidate(new AddShoppingListCommand { 
        Name = command.Name, UserId = UserId});
            
        if (!result.IsValid) {
            return View(command);
        }

        TempData["Success"] = "List zakupów została dodana";

        return RedirectToAction("ShoppingLists");
    }

    public async Task<IActionResult> EditShoppingList(int id) {

        return View(await Mediator.Send(
            new GetEditShoppingListQuery { Id = id, UserId = UserId }));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditShoppingList(EditShoppingListCommand command) {

        var result = await MediatorSendValidate(command);

        if(!result.IsValid)
            return View(command);

        TempData["Success"] = "Nazwa listy została zaktualizowana";

        return RedirectToAction("ShoppingLists");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteShoppingList(int id) {

        try {
            await Mediator.Send(new DeleteShoppingListCommand
            {
                Id = id,
                UserId = UserId
            });

            return Json( new { success = true });
        }
        catch (Exception exception){
            _logger.LogError(exception, null);

            return Json(new {success = false});
        }
    }

    public async Task<IActionResult> ChildShoppingLists(int id) {

        return View(await Mediator.Send(new GetChildShoppingListsQuery 
        { UserId = UserId,
          ParentShoppingListId = id
        }));
    }

    



}

ColoradoBeetle.UI/Views/Basic/ShoppingList/AddShoppingList.cshtml
@using ColoradoBeetle.Application.ShoppingLists.Commands.AddShopinngList;

@model AddShoppingListCommand

@{
    ViewData["Title"] = "Dodawanie nowej listy";
}

<div class="card card-primary card-border-top privateUser-bg">

    @using (Html.BeginForm("AddShoppingList, ShoppingList")) 
    {  
        @Html.AntiForgeryToken()

        <div class="card-body">
            <div class="form-group">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name, new { @class="form-control"
                    , placeholder="Brak nazwy = aktualna data"})
                @Html.ValidationMessageFor(x => x.Name)
            </div>

        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary btn-lg">
                <i class="fas fa-solid fa-circle-check"></i>Zapisz
            </button>

        </div>
        
    }
</div>

@section Scripts{
    <partial name="Scripts/_ValidationScriptsPartial" />
}

ColoradoBeetle.UI/Views/Basic/ShoppingList/ChildShoppingLists.cshtml
@using ColoradoBeetle.Application.Roles.Queries.GetRoles;
@using System.Globalization;
@using ColoradoBeetle.Application.ShoppingLists.Queries.GetChildShoppingLists;
@using ColoradoBeetle.Application.ShoppingLists.Queries.GetShoppingLists;
@model GetChildShoppingListsVm;

@{
    ViewData["Title"] = "Listy do skopiowania";
    var locale = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
}

@section Styles {
    <partial name="Styles/_DataTablesStyles" />
}


<div class="card card-primary card-border-top privateUser-bg">

    <div class="card-body">

        <table id="shoppingLists" class="table table-bordered bg-white">
            <thead>
                <tr>
                    <th></th>
                        <th>Nazwa listy</th>
                    <th class="desktop"></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var childShoppingList in Model.ChildShoppingLists) {
                    <tr>
                        <td>@childShoppingList.Id</td>
                        <td>
                            @childShoppingList.Name
                        </td>
                        <td>
                            <div class="d-flex flex-row">
                                <div class="m-1">
                                    <a class="btn btn-success btn-sm" role="button"
                                       href='/Product/CopyAllProducts?id=@childShoppingList.Id&prntId=@Model.ParentShoppingListId'>
                                        <i class="fas fa-regular fa-folder-open"></i>Wszystkie produkty
                                    </a>
                                </div>
                                <div class="m-1">
                                    <a class="btn btn-primary btn-sm" role="button"
                                       href='/Product/GetChildProducts?id=@childShoppingList.Id&prntId=@Model.ParentShoppingListId'>
                                        <i class="fas fa-regular fa-file"></i>Wybierz pojedyńczo
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>



@section Scripts {
    <partial name="Scripts/_DataTablesScripts" />

    <script>

        var selectedRow;
        var selectedShoppingListId = 0;
        var shoppingLists;

        $(document).ready(function () {

            shoppingLists = $('#shoppingLists').DataTable({
                paging: true,
                ordering: true,
                info: true,
                responsive: true,
                autoWidth: false,
                lengthChange: true,
                lengthMenu: [25, 50, 75, 100],
                language: {
                    url: `/lib/datatables/lang/${'@locale'}.json`
                },
                order: [[0, "desc"]],
                columnDefs: [
                    {
                        targets: [0],
                        visible: false,
                        searchable: false
                    }]
            });
        });
    </script>
}

ColoradoBeetle.UI/Views/Basic/ShoppingList/EditShoppingList.cshtml
@using ColoradoBeetle.Application.ShoppingLists.Commands.EditShoppingList;
@model EditShoppingListCommand

@{
    ViewData["Title"] = "Aktualizowanie listy";
}

<div class="card card-primary card-border-top privateUser-bg">

    @using (Html.BeginForm("EditShoppingList", "ShoppingList")) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id)
        @Html.HiddenFor(x => x.UserId)

        <div class="card-body">
            <div class="form-group">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name, new {@class="form-control", 
                    placeholder="Wprowadź nową nazwę"})
                @Html.ValidationMessageFor(x => x.Name)
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary btn-lg">
                <i class="fas fa-solid fa-circle-check"></i>Zapisz
            </button>
        </div>

    }

</div>

ColoradoBeetle.UI/Views/Basic/ShoppingList/ShoppingLists.cshtml
@using ColoradoBeetle.Application.Roles.Queries.GetRoles;
@using System.Globalization;
@using ColoradoBeetle.Application.ShoppingLists.Queries.GetShoppingLists;
@model IEnumerable<ShoppingListDto>

@{
    ViewData["Title"] = "Listy zakupów";
    var locale = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
}

@section Styles {
    <partial name="Styles/_DataTablesStyles" />
}

<partial name="Modals/_ModalConfirm"
         model="@(new ModalParams
{
    Id = "modal-confirm-delete",
    Title = "Potwierdź proszę",
    Description = "Czy na pewno chcesz usunąć wybraną listę?"
})" />



<div class="card card-primary card-border-top">
    
    <div class="card-body privateUser-bg">

        <a href='/ShoppingList/AddShoppingList' class="btn btn-primary mb-3" role="button">
            <i class="fas fa-solid fa-circle-plus"></i>Dodaj nową listę 
        </a>

        
        <table id="shoppingLists" class="table table-bordered bg-white">
            <thead>
                <tr>
                    <th></th>
                    <th>Nazwa listy</th>
                    <th class="desktop"></th>
                </tr>
            </thead>
            <tbody>

                @foreach(var shoppingList in Model) {
                    <tr>
                        <td>
                            @shoppingList.CreatedDate
                        </td>
                        <td>
                            @shoppingList.Name
                        </td>
                        <td>
                            <div class="d-flex flex-row">
                                <div class="m-1">
                                    <a class="btn btn-primary btn-sm" role="button"
                                       href='/Product/GetProductsInList?id=@shoppingList.Id'>
                                        <i class="fas fa-solid fa-square-plus"></i>Produkty
                                    </a>
                                </div>
                                <div class="m-1">
                                    <a class="btn btn-success btn-sm" role="button"
                                       href='/ShoppingList/EditShoppingList?id=@shoppingList.Id'>
                                        <i class="fas fa-solid fa-magnifying-glass"></i>Edytuj
                                    </a>
                                </div>
                                <div class="m-1">
                                    <button class="btn btn-danger btn-sm"
                                            onclick="deleteShoppingList('@shoppingList.Id', this)">
                                        <i class="fas fa-solid fa-trash-can"></i>Usuń
                                    </button>
                                </div>
                            </div>
                        </td>
                       
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>



@section Scripts {
    <partial name="Scripts/_DataTablesScripts" />

    <script>

        var selectedRow;
        var selectedShoppingListId = 0;
        var shoppingLists;

        $(document).ready(function () {
            
            shoppingLists = $('#shoppingLists').DataTable({
                paging: true,
                ordering: true,
                info: true,
                responsive: true,
                autoWidth: false,
                lengthChange: true,
                lengthMenu: [25, 50, 75, 100],
                language: {
                    url: `/lib/datatables/lang/${'@locale'}.json`
                },
                order: [[0, "desc"]],
                columnDefs: [
                {
                    targets: [0],
                    visible: false,
                    searchable: false
                }]
            });
        });


        function deleteShoppingList(id, btn) {
            selectedRow = btn.parentNode.parentNode.parentNode.parentNode;
            selectedShoppingListId = id;
            $('#modal-confirm-delete').modal('show');
        }

        $('#modal-confirm-delete-btn').on('click', function (e) {
            $('#modal-confirm-delete').modal('hide');

            $.ajax({
                type: "POST",
                url: "/ShoppingList/DeleteShoppingList",
                data: {
                    id: selectedShoppingListId
                },
                success: function(data) {
                    if(data.success){
                        shoppingLists.rows(selectedRow).remove().draw();
                        toastr.success("Lista została usunięta.");
                    }
                    else{
                        toastr.error('Błąd. Nie udało się usunąć wybranej listy. Spróbuj ponownie lub skontaktuj się z administratorem');
                    }
                },
                error: function (data) {
                    toastr.error('Błąd. Nie udało się usunąć wybranej listy. Spróbuj ponownie lub skontaktuj się z administratorem');
                    
                },
                dataType: "json"
            });
        });
    </script>
}