ColoradoBeetle.UI/Components/MainCarouselViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ColoradoBeetle.UI.Components; 
public class MainCarouselViewComponent : ViewComponent{
    public async Task<IViewComponentResult> InvokeAsync(string testComponents) {
        //logic
        return View();
    }
}

ColoradoBeetle.UI/Controllers/HomeController.cs
using AspNetCore.ReCaptcha;
using ColoradoBeetle.Application.Common.Exceptions;
using ColoradoBeetle.Application.Contacts.Commands.SendContactEmail;
using Microsoft.AspNetCore.Mvc;

namespace ColoradoBeetle.UI.Controllers {
    public class HomeController : BaseController {
        private readonly ILogger _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }
        public async Task<IActionResult> Index() {

            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        public IActionResult Contact() {
            return View(new SendContactEmailCommand());
        }

        [ValidateReCaptcha]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Contact(SendContactEmailCommand command) {

            var result = await MediatorSendValidate(command);

            if (!result.IsValid) {

                ModelState.AddModelError("AntySpamResult", "Wypełnij pole ReCaptcha (zabezpieczenie " +
                    "przed spamem)");
                return View(command);
            }

            TempData["Success"] = "Widomość została wysłana do administratora.";

            return RedirectToAction("Contact");
        }


    }
}

ColoradoBeetle.UI/Views/Basic/Home/Contact.cshtml
@using AspNetCore.ReCaptcha;
@using ColoradoBeetle.Application.Contacts.Commands.SendContactEmail;
@inject IConfiguration configuration
@model SendContactEmailCommand

@{
    var templateKey = configuration.GetSection("TemplateKey").Value;
    Layout = $"/Views/{templateKey}/Shared/_LayoutMain.cshtml";
    ViewData["Title"] = "Kontakt";
}

@section Styles{
    <link rel="stylesheet" href="~/lib/toastr.js/toastr.min.css" />
}

@await Component.InvokeAsync("MainCarousel", "testComp");

<div class="container">
    <div class="row mt-3 mb-5">

        <h1>
            @ViewBag.Title
        </h1>

        @using (Html.BeginForm("Contact", "Home")) {
            
            @Html.AntiForgeryToken();

            <div class="form-group mt-3">
                @Html.TextBoxFor(x => x.Name, new {@class="form-control", placeholder="Imię i nazwisko"})
                @Html.ValidationMessageFor(x => x.Name)
            </div>

            <div class="form-group mt-3">
                @Html.TextBoxFor(x => x.Email, new {@class="form-control", placeholder="Email"})
                @Html.ValidationMessageFor(x => x.Email)
            </div>

            <div class="form-group mt-3">
                @Html.TextBoxFor(x => x.Title, new {@class="form-control", placeholder="Tytuł wiadomości"})
                @Html.ValidationMessageFor(x => x.Title)
            </div>

            <div class="form-group mt-3">
                @Html.TextAreaFor(x => x.Message, new {@class="form-control", placeholder="Wiadomość"
            , @rows=4})
                @Html.ValidationMessageFor(x => x.Message)
            </div>

            <div class="mt-3"></div>

            <div class="form-group">
                @Html.HiddenFor(x => x.AntySpamResult)
                @Html.ValidationMessageFor(x => x.AntySpamResult)
            </div>

            @Html.ReCaptcha()

            <button type="submit" class="btn btn-primary btn-lg mt-4">
                <i class="fas fa-solid fa-circle-check"></i>Wyślij wiadomość
            </button>
        }
    </div>
</div>

@section Scripts{
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <partial name="Scripts/_ValidationScriptsPartial"/>
    <partial name="_NotificationPartial"/>
}

ColoradoBeetle.UI/Views/Basic/Home/Index.cshtml
@inject IConfiguration configuration

@{
    var templateKey = configuration.GetSection("TemplateKey").Value;
    Layout = $"/Views/{templateKey}/Shared/_LayoutMain.cshtml";
    ViewData["Title"] = "Strona Główna";
}

@await Component.InvokeAsync("MainCarousel", "testComp");

<div class="bg-light">
    <div class="container">
        <div class="row">
            <figure class="text-center p-5">
                <blockquote class=blockquote>
                    <p>
                        Szansa jedna na milion udaje się przeciętnie dziewięć razy na dziesięć.
                    </p>
                </blockquote>
                <figcaption class="blockquote-footer mt-3 secondary-description">
                    Terry Pratchet <cite title="Source Title">Straż! Straż!</cite>
                </figcaption>
            </figure>
        </div>
    </div>
</div>